### ISSUE TITLE
Typo in Japan example?

### ISSUE THREAD

**Issue by wcandillon** [28msec/cellstore#591]
In `report-elements.jq`, `cik` is documented as sec only.
However the edinet example is as:
http://edinet.28.io/v1/_queries/public/api/report-elements.jq?_method=POST&token=54eb0587-1aee-44a5-bb56-627f6ef43da6&cik=E01225&format=json&profile-name=japan&label=%22Loss%20of%20inactive%20facilities%22

Is it a typo where it should eid instead of cik?

**Comment by gislenius** [comment]
Hi William,

No. The EID is the long entity ID that includes the scheme as well. The CIK
is the shortcut version, that corresponds to the "official public"
identifier of the firm. I just reused the cik parameter for that because
it's the same semantics as in SEC.

Kind regards,
Ghislain


On Wed, Jan 7, 2015 at 10:49 PM, William Candillon <notifications@github.com

**Comment by wcandillon** [comment]
Is the resolution of the bug report to use the eid parameter instead of cik in the example?

There seems to be a contradiction between the documentation (which documents cik as sec specific) and the implementation which allows it in a non sec context.
