### ISSUE TITLE
odd behavior with spreadsheet-for-component for several years

### ISSUE THREAD

**Issue by dknochen** [28msec/cellstore#920]
http://rendering.secxbrl.info/#?url=https:%2F%2Fsecxbrl.28.io%2Fv1%2F_queries%2Fpublic%2Fapi%2Fspreadsheet-for-component.jq%3Ftoken%3Dc3049752-4d35-43da-82a2-f89f1b06f7a4%26format%3Djson%26%26cik%3D0000804328%26fiscalYear%3D2013%26fiscalPeriod%3DFY%26fiscalPeriodType%3DYTD%26fiscalPeriodType%3Dinstant%26disclosure%3DIncomeStatement%26override%3Dtrue

![image](https://cloud.githubusercontent.com/assets/1012324/7103580/e92175ec-e0ad-11e4-8700-fcb95a74fa4c.png)

The value for "Licensing" for 2013 disappears if the year 2014 is added:

http://rendering.secxbrl.info/#?url=https:%2F%2Fsecxbrl.28.io%2Fv1%2F_queries%2Fpublic%2Fapi%2Fspreadsheet-for-component.jq%3Ftoken%3Dc3049752-4d35-43da-82a2-f89f1b06f7a4%26format%3Djson%26%26cik%3D0000804328%26fiscalYear%3D2013%26fiscalYear%3D2014%26fiscalPeriod%3DFY%26fiscalPeriodType%3DYTD%26fiscalPeriodType%3Dinstant%26disclosure%3DIncomeStatement%26override%3Dtrue

![image](https://cloud.githubusercontent.com/assets/1012324/7103584/180eccb0-e0ae-11e4-81b0-82f72284421b.png)

**Comment by dknochen** [comment]
some more values disappear if 2012 is added:

http://rendering.secxbrl.info/#?url=https:%2F%2Fsecxbrl.28.io%2Fv1%2F_queries%2Fpublic%2Fapi%2Fspreadsheet-for-component.jq%3Ftoken%3Dc3049752-4d35-43da-82a2-f89f1b06f7a4%26format%3Djson%26%26cik%3D0000804328%26fiscalYear%3D2012%26fiscalYear%3D2013%26fiscalYear%3D2014%26fiscalPeriod%3DFY%26fiscalPeriodType%3DYTD%26fiscalPeriodType%3Dinstant%26disclosure%3DIncomeStatement%26override%3Dtrue

![image](https://cloud.githubusercontent.com/assets/1012324/7103606/bc28aa22-e0af-11e4-9d88-19c4e44c5c6d.png)

**Comment by gislenius** [comment]
Hi Dennis,

That's because the two years use different names even though it's the same label.

You need to add merge=true to merge the components rather than pick the hierarchy from the first one.

http://rendering.secxbrl.info/#?url=http:%2F%2Fsecxbrl.28.io:80%2Fv1%2F_queries%2Fpublic%2Fapi%2Fspreadsheet-for-component.jq%3Ftoken%3Dc3049752-4d35-43da-82a2-f89f1b06f7a4%26format%3Djson%26cik%3D0000804328%26fiscalYear%3D2013%26fiscalYear%3D2014%26fiscalPeriod%3DFY%26fiscalPeriodType%3DYTD%26fiscalPeriodType%3Dinstant%26disclosure%3DIncomeStatement%26override%3Dtrue%26merge%3Dtrue

Kind regards,
Ghislain

**Comment by gislenius** [comment]
And in the second case:

http://rendering.secxbrl.info/#?url=https:%2F%2Fsecxbrl.28.io%2Fv1%2F_queries%2Fpublic%2Fapi%2Fspreadsheet-for-component.jq%3Ftoken%3Dc3049752-4d35-43da-82a2-f89f1b06f7a4%26format%3Djson%26%26cik%3D0000804328%26fiscalYear%3D2012%26fiscalYear%3D2013%26fiscalYear%3D2014%26fiscalPeriod%3DFY%26fiscalPeriodType%3DYTD%26fiscalPeriodType%3Dinstant%26disclosure%3DIncomeStatement%26override%3Dtrue%26merge%3Dtrue

**Comment by dknochen** [comment]
@gislenius thanks for your responses! Do you think we could make merge=true the default behavior?
